name: Build

on:
  push

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Dart SDK
      run: |
        sudo apt install apt-transport-https
        sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | tee /etc/apt/trusted.gpg.d/dartlang.org.asc'
        sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'

    - name: Install Dart SDK
      run: |
        sudo apt update
        sudo apt install dart
    
    - name: dart pub get
      run: /usr/lib/dart/bin/dart pub get
    
    # disabled - some bit rot occurred on original repo, tests do not work
    # - name: Run unit tests
    #  run: /usr/lib/dart/bin/dart run test ./test/all_test.dart --platform vm
    
    - name: Prepare dist directory and copy docs
      run: |
        mkdir dist
        cp -r deluge-docs dist

    - name: Build AOT target
      run: /usr/lib/dart/bin/dart compile aot-snapshot bin/main.dart -o dist/DelugeParser.aot

    - name: Build executable target
      run: /usr/lib/dart/bin/dart compile exe bin/main.dart -o dist/DelugeParser
    
    # disabled - resulting artifact is only usable on build system due to deps
    # - name: Build JavaScript target
    #   run: /usr/lib/dart/bin/dart compile js bin/main.dart -o dist/DelugeParser.js

    - name: Publish build artifact
      uses: actions/upload-artifact@v3
      with:
        name: deluge-lsp-aot
        path: dist/
